### ISSUE TITLE
Catalogue v2.1.0 depends on dependencies not declared

### ISSUE THREAD

**Issue by schorfma** [explosion/catalogue#46]
Hello,

I just noticed that the `catalogue` version [`v2.1.0`](https://github.com/explosion/catalogue/tree/v2.1.0) (Most recent version on PyPI currently) depends on dependencies not declared in the setup related files.
This is probably due to the temporary inclusion of the config system, which now lives in [`confection`](https://github.com/explosion/confection) (#33).

The traceback when importing `catalogue` is the following:

```sh
Traceback (most recent call last):
  File "...", line 8, in <module>
    from functions import FUNCTIONS
  File "./functions.py", line 1, in <module>
    import catalogue
  File ".../lib/python3.10/site-packages/catalogue/__init__.py", line 2, in <module>
    from catalogue.config import *
  File ".../lib/python3.10/site-packages/catalogue/config/__init__.py", line 1, in <module>
    from .config import *
  File ".../lib/python3.10/site-packages/catalogue/config/config.py", line 10, in <module>
    from pydantic import BaseModel, create_model, ValidationError, Extra
ModuleNotFoundError: No module named 'pydantic'
```

When installing `pydantic` to fix the problem, the traceback states it cannot find `srsly`.

**Comment by adrianeboyd** [comment]
This version is yanked on PyPI (you should see a red "YANKED" button next to it, https://pypi.org/help/#yanked), which means that it's preserved for posterity, but if you run `pip install catalogue` it will never select this release. It was yanked because of problems with the dependencies and shouldn't be used.

**Comment by schorfma** [comment]
> This version is yanked on PyPI (you should see a red "YANKED" button next to it, https://pypi.org/help/#yanked), which means that it's preserved for posterity, but if you run `pip install catalogue` it will never select this release. It was yanked because of problems with the dependencies and shouldn't be used.

Thank you, ah I understand. Then the problem lies within `poetry` which selected that version despite the `YANKED` flag 🙄.

**Comment by adrianeboyd** [comment]
Ah, that is frustrating. It looks like the most recent release of poetry should recognize yanked releases at least?

To be honest we could just delete it from pypi because there's no reason anyone should ever use it.

**Comment by schorfma** [comment]
I used `poetry` version `1.1.13` from February 2022.

Fortunately in the most recent `poetry` version `1.2.1` it works as expected.

```sh
❯ poetry add catalogue
Using version ^2.0.8 for catalogue

Updating dependencies
Resolving dependencies... (0.8s)

Writing lock file

Package operations: 0 installs, 16 updates, 0 removals

  • Updating [...]
  [...]
Warning: The file chosen for install of catalogue 2.1.0 (catalogue-2.1.0-py3-none-any.whl) is yanked.
```
